import { Imovel } from '@/types/imovel';

export const MOCK_IMOVEIS: Imovel[] = [
  {
    _id: "1",
    codigo: "YAN-0458",
    titulo: "Apartamento no Jardim América",
    slug: { current: "apartamento-jardim-america" },
    tipoNegocio: "venda",
    tipoImovel: "apartamento",
    valor: 850000,
    cidade: "São Paulo",
    bairro: "Jardim América",
    endereco: "Rua Estados Unidos, 123",
    quartos: 3,
    banheiros: 2,
    vagas: 2,
    areaPrivativa: 120,
    descricao: "Apartamento moderno e sofisticado no coração do Jardim América, ideal para quem busca conforto e elegância. Com amplos espaços, acabamentos de alto padrão e uma localização privilegiada perto de tudo o que você precisa. O prédio oferece segurança 24h e lazer completo.",
    comodidades: ["Piscina", "Academia", "Churrasqueira", "Salão de festas", "Portaria 24h"],
    latitude: -23.5615,
    longitude: -46.6668,
    fotos: [{ asset: { url: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800" } }, { asset: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800" } }],
    destaque: true,
    status: "ativo"
  },
  {
    _id: "2",
    codigo: "YAN-0921",
    titulo: "Casa de Alto Padrão no Cambuí",
    slug: { current: "casa-cambui" },
    tipoNegocio: "venda",
    tipoImovel: "casa",
    valor: 2200000,
    cidade: "Campinas",
    bairro: "Cambuí",
    endereco: "Rua Sampaio Ferraz, 456",
    quartos: 4,
    banheiros: 4,
    vagas: 4,
    areaPrivativa: 350,
    descricao: "Casa espaçosa em um dos bairros mais desejados de Campinas. Perfeita para famílias que buscam privacidade e lazer em um só lugar.",
    comodidades: ["Piscina", "Espaço Gourmet", "Jardim", "Segurança 24h"],
    latitude: -22.8989,
    longitude: -47.0505,
    fotos: [{ asset: { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800" } }],
    destaque: true,
    status: "ativo"
  },
  {
    _id: "3",
    codigo: "YAN-1102",
    titulo: "Studio Contemporâneo no Centro",
    slug: { current: "studio-centro" },
    tipoNegocio: "locacao",
    tipoImovel: "apartamento",
    valor: 3500,
    cidade: "Campinas",
    bairro: "Centro",
    endereco: "Av. Francisco Glicério, 1000",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    areaPrivativa: 45,
    descricao: "Studio moderno com excelente localização, próximo a bancos, restaurantes e comércio central. Ideal para jovens profissionais.",
    comodidades: ["Lavanderia", "Academia", "Coworking"],
    latitude: -22.9056,
    longitude: -47.0608,
    fotos: [{ asset: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800" } }],
    destaque: false,
    status: "ativo"
  },
  {
    _id: "4",
    codigo: "YAN-2233",
    titulo: "Sala Comercial na Norte-Sul",
    slug: { current: "sala-comercial-norte-sul" },
    tipoNegocio: "locacao",
    tipoImovel: "comercial",
    valor: 6000,
    cidade: "Campinas",
    bairro: "Jardim Planalto",
    endereco: "Av. José de Souza Campos, 2000",
    quartos: 0,
    banheiros: 2,
    vagas: 2,
    areaPrivativa: 90,
    descricao: "Sala comercial ampla em prédio de alto padrão, localização estratégica na principal avenida de Campinas.",
    comodidades: ["Elevador", "Portaria 24h", "Auditório"],
    latitude: -22.9090,
    longitude: -47.0450,
    fotos: [{ asset: { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800" } }],
    destaque: true,
    status: "ativo"
  }
];
